# Generated by Django 4.1.1 on 2022-10-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='static/media/images/user/')),
                ('gender', models.CharField(choices=[('lehilahy', 'lehilahy'), ('vehivavy', 'vehivavy')], default='lehilahy', max_length=8)),
                ('tel', models.IntegerField()),
                ('mail', models.EmailField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=200)),
                ('repeate', models.CharField(max_length=200)),
            ],
        ),
    ]
