# Generated by Django 4.1.1 on 2022-10-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_address_alter_user_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=50)),
                ('id_owner', models.IntegerField()),
                ('id_authorised', models.CharField(max_length=50)),
            ],
        ),
    ]
