# Generated by Django 4.1.1 on 2022-10-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mofonaina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('author', models.IntegerField()),
                ('content', models.TextField()),
                ('media', models.FileField(null=True, upload_to='static/media/mofonaina/')),
                ('lector', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='superuser',
            name='id_authorised',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
