# Generated by Django 4.1.1 on 2022-10-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_mofonaina_alter_superuser_id_authorised'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mofonaina',
            old_name='author',
            new_name='author_id',
        ),
        migrations.AddField(
            model_name='mofonaina',
            name='author_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
