# Generated by Django 4.1.1 on 2022-10-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_author_mofonaina_author_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mofonaina',
            name='media',
        ),
    ]
