# Generated by Django 4.1.1 on 2022-10-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_mofonaina_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperUser',
        ),
    ]
