# Generated by Django 4.1.1 on 2022-10-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_archive_asa_sampana'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampana',
            name='famariparitana',
            field=models.CharField(default=' famariparitana values ', max_length=200),
            preserve_default=False,
        ),
    ]
