# Generated by Django 4.1.1 on 2022-10-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_sampana_famariparitana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rafitra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('sudo', models.CharField(max_length=20)),
                ('picture', models.FileField(upload_to='static/images/sampana/rafitra')),
                ('name', models.CharField(max_length=10)),
                ('function', models.CharField(max_length=20)),
            ],
        ),
    ]
