# Generated by Django 4.1.1 on 2022-10-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rafitra'),
    ]

    operations = [
        migrations.AddField(
            model_name='asa',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='asa',
            name='title',
            field=models.CharField(default='titre', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rafitra',
            name='picture',
            field=models.FileField(upload_to=' /app/static/images/sampana/rafitra'),
        ),
    ]
