# Generated by Django 4.1.1 on 2022-10-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_vaovao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaovao',
            name='sokajy',
            field=models.CharField(default='filazana', max_length=30),
            preserve_default=False,
        ),
    ]
