# Generated by Django 4.1.1 on 2022-10-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_vaovao_sokajy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fandaharana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
