# Generated by Django 4.1.1 on 2022-11-01 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_fandaharana_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mofonaina',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='mofonaina',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='mofonaina',
            name='lector',
        ),
    ]
